/// Flutter icons Ranking
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Ranking
///      fonts:
///       - asset: fonts/Ranking.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class Ranking {
  Ranking._();

  static const _kFontFam = 'Ranking';
  static const String? _kFontPkg = null;

  static const IconData podium = IconData(0xea70, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
